### ISSUE TITLE
Can't find the target after building

### ISSUE THREAD

**Issue by yakir12** [LarsHaalck/CATER#16]
Although the README states that
> the binary of the CATER-Gui should be compiled in build `/ui/gui/cater-gui`

After successfully building it locally

<details>
  <summary>Stack trace</summary>
<code>
$ make -j8
[  2%] Performing update step for 'spdlog_external'
[  2%] Performing update step for 'eigen3_external'
[  3%] Performing update step for 'cxxopts_external'
[ 13%] Built target qt6base_external
[ 23%] Built target qt6shadertools_external
-- cxxopts_external update command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/cxxopts_external/cxxopts_external-update-*.log
-- spdlog_external update command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/spdlog_external/spdlog_external-update-*.log
[ 25%] No patch step for 'cxxopts_external'
[ 26%] No patch step for 'spdlog_external'
[ 36%] Built target qt6multimedia_external
[ 37%] Performing configure step for 'cxxopts_external'
[ 38%] Performing configure step for 'spdlog_external'
-- cxxopts_external configure command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/cxxopts_external/cxxopts_external-configure-*.log
[ 40%] Performing build step for 'cxxopts_external'
-- spdlog_external configure command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/spdlog_external/spdlog_external-configure-*.log
[ 41%] Performing build step for 'spdlog_external'
-- cxxopts_external build command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/cxxopts_external/cxxopts_external-build-*.log
[ 42%] Performing install step for 'cxxopts_external'
-- spdlog_external build command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/spdlog_external/spdlog_external-build-*.log
-- cxxopts_external install command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/cxxopts_external/cxxopts_external-install-*.log
[ 43%] Performing install step for 'spdlog_external'
[ 45%] Completed 'cxxopts_external'
[ 47%] Built target cxxopts_external
-- spdlog_external install command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/spdlog_external/spdlog_external-install-*.log
[ 48%] Completed 'spdlog_external'
[ 51%] Built target spdlog_external
-- eigen3_external update command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/eigen3_external/eigen3_external-update-*.log
[ 52%] No patch step for 'eigen3_external'
[ 53%] Performing configure step for 'eigen3_external'
-- eigen3_external configure command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/eigen3_external/eigen3_external-configure-*.log
[ 55%] Performing build step for 'eigen3_external'
-- eigen3_external build command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/eigen3_external/eigen3_external-build-*.log
[ 56%] Performing install step for 'eigen3_external'
-- eigen3_external install command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/eigen3_external/eigen3_external-install-*.log
[ 57%] Completed 'eigen3_external'
[ 60%] Built target eigen3_external
[ 62%] Performing update step for 'mild_external'
[ 62%] Performing update step for 'ceres_external'
[ 63%] Performing update step for 'cereal_external'
-- ceres_external update command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/ceres_external/ceres_external-update-*.log
-- cereal_external update command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/cereal_external/cereal_external-update-*.log
[ 66%] No patch step for 'ceres_external'
[ 66%] No patch step for 'cereal_external'
[ 68%] Performing configure step for 'cereal_external'
[ 68%] Performing configure step for 'ceres_external'
CMake Warning (dev) at /home/yakir/tmp/CATER/build/external/Stamp/ceres_external/ceres_external-configure-Release.cmake:4:
  Syntax Warning in cmake code at column 258
  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- cereal_external configure command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/cereal_external/cereal_external-configure-*.log
[ 70%] Performing build step for 'cereal_external'
-- cereal_external build command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/cereal_external/cereal_external-build-*.log
[ 71%] Performing install step for 'cereal_external'
-- cereal_external install command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/cereal_external/cereal_external-install-*.log
[ 72%] Completed 'cereal_external'
[ 75%] Built target cereal_external
-- ceres_external configure command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/ceres_external/ceres_external-configure-*.log
[ 76%] Performing build step for 'ceres_external'
-- mild_external update command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/mild_external/mild_external-update-*.log
[ 77%] No patch step for 'mild_external'
[ 78%] Performing configure step for 'mild_external'
-- mild_external configure command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/mild_external/mild_external-configure-*.log
[ 80%] Performing build step for 'mild_external'
-- mild_external build command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/mild_external/mild_external-build-*.log
[ 81%] Performing install step for 'mild_external'
-- mild_external install command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/mild_external/mild_external-install-*.log
[ 82%] Completed 'mild_external'
[ 85%] Built target mild_external
-- ceres_external build command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/ceres_external/ceres_external-build-*.log
[ 86%] Performing install step for 'ceres_external'
-- ceres_external install command succeeded.  See also /home/yakir/tmp/CATER/build/external/Stamp/ceres_external/ceres_external-install-*.log
[ 87%] Completed 'ceres_external'
[ 90%] Built target ceres_external
[ 91%] Performing configure step for 'cater'
-- Found required Ceres dependency: Eigen version 3.4.1 in /home/yakir/tmp/CATER/build/stage/share/eigen3/cmake
-- Found Ceres compiled with miniglog substitute for glog, beware this will likely cause problems if glog is later linked.
-- Found Ceres version: 2.1.0 installed in: /home/yakir/tmp/CATER/build/stage with components: [EigenSparse, SparseLinearAlgebraLibrary, SchurSpecializations, Multithreading]
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /home/yakir/tmp/CATER/build/external/Build/cater
[ 92%] Performing build step for 'cater'
[  4%] Built target cache_STATIC
[  7%] Built target progressbar_STATIC
[ 12%] Built target util_STATIC
[ 50%] Built target image-processing_STATIC
[ 62%] Built target tracker_STATIC
[ 81%] Built target model_STATIC
[ 95%] Built target panorama_STATIC
[100%] Built target cater-tui
[ 93%] No install step for 'cater'
[ 95%] Completed 'cater'
[100%] Built target cater
</code>
</details>

I can't find any trace of the `cater-gui` executable target:
```
 find . -type f -name "*cater-gui*"
./ui/gui/cater/resources/cater-gui.png
./ui/gui/cater/resources/cater-gui.desktop
```

**Comment by LarsHaalck** [comment]
I changed something a few months ago and forgot to update the readme, sorry. 
There is an option `BUILD_GUI` that needs to be passed to cmake.
The binary is then in `external/Build/cater/ui/gui/cater/cater-gui`

**Comment by yakir12** [comment]
I can confirm that this issue is now resolved (you might want to add a note that parallel `make`ing, ie `make -j8`, is however not possible).
